select *
from TIL_DATA_ENGINEERING.aea_lk_raw.raw_balancing_authority_interchange;

select *
from TIL_DATA_ENGINEERING.aea_lk_stage.stg_balancing_authority_interchange;

select *
from TIL_DATA_ENGINEERING.aea_lk_intermediate.fact_balancing_authority_interchange;

select *
from TIL_DATA_ENGINEERING.aea_lk_mart.mart_grid_interchange_summary;