-- 1. REGIONAL OPERATING METRICS
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_REGIONAL_OPERATING_METRICS DROP COLUMN IF EXISTS utc_tmp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_REGIONAL_OPERATING_METRICS ADD COLUMN utc_tmp TIMESTAMP_NTZ;
UPDATE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_REGIONAL_OPERATING_METRICS SET utc_tmp = TRY_TO_TIMESTAMP(utc_response_timestamp);
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_REGIONAL_OPERATING_METRICS DROP COLUMN utc_response_timestamp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_REGIONAL_OPERATING_METRICS RENAME COLUMN utc_tmp TO utc_response_timestamp;

-- 2. GENERATION ENERGY SOURCE
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_GENERATION_ENERGY_SOURCE DROP COLUMN IF EXISTS utc_tmp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_GENERATION_ENERGY_SOURCE ADD COLUMN utc_tmp TIMESTAMP_NTZ;
UPDATE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_GENERATION_ENERGY_SOURCE SET utc_tmp = TRY_TO_TIMESTAMP(utc_response_timestamp);
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_GENERATION_ENERGY_SOURCE DROP COLUMN utc_response_timestamp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_GENERATION_ENERGY_SOURCE RENAME COLUMN utc_tmp TO utc_response_timestamp;

-- 3. SUBREGIONAL DEMAND
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_SUBREGIONAL_DEMAND DROP COLUMN IF EXISTS utc_tmp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_SUBREGIONAL_DEMAND ADD COLUMN utc_tmp TIMESTAMP_NTZ;
UPDATE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_SUBREGIONAL_DEMAND SET utc_tmp = TRY_TO_TIMESTAMP(utc_response_timestamp);
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_SUBREGIONAL_DEMAND DROP COLUMN utc_response_timestamp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_SUBREGIONAL_DEMAND RENAME COLUMN utc_tmp TO utc_response_timestamp;

-- 4. BALANCING AUTHORITY INTERCHANGE
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_BALANCING_AUTHORITY_INTERCHANGE DROP COLUMN IF EXISTS utc_tmp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_BALANCING_AUTHORITY_INTERCHANGE ADD COLUMN utc_tmp TIMESTAMP_NTZ;
UPDATE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_BALANCING_AUTHORITY_INTERCHANGE SET utc_tmp = TRY_TO_TIMESTAMP(utc_response_timestamp);
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_BALANCING_AUTHORITY_INTERCHANGE DROP COLUMN utc_response_timestamp;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_BALANCING_AUTHORITY_INTERCHANGE RENAME COLUMN utc_tmp TO utc_response_timestamp;