DROP SCHEMA IF EXISTS TIL_DATA_ENGINEERING.AEA_LK_STAGE CASCADE;
DROP SCHEMA IF EXISTS TIL_DATA_ENGINEERING.AEA_LK_INTERMEDIATE CASCADE;
DROP SCHEMA IF EXISTS TIL_DATA_ENGINEERING.AEA_LK_MART CASCADE;

select *
from til_data_engineering.AEA_LK_STAGE.stg_generation;


ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_REGIONAL_OPERATING_METRICS ADD COLUMN payload_hash VARCHAR;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_GENERATION_ENERGY_SOURCE ADD COLUMN payload_hash VARCHAR;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_SUBREGIONAL_DEMAND ADD COLUMN payload_hash VARCHAR;
ALTER TABLE TIL_DATA_ENGINEERING.AEA_LK_RAW.RAW_BALANCING_AUTHORITY_INTERCHANGE ADD COLUMN payload_hash VARCHAR;