transformer:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      role: "ACCOUNTADMIN"
      database: "TIL_DATA_ENGINEERING"
      warehouse: "DATASCHOOL_WH"
      schema: "AEA_LK"
      threads: 4
